site_name: L06P Software - Supervision Modules Documentation
site_description: Documentation dédiés aux Modules de Supervision édités par L06P Software
copyright: Copyright &copy; 2024 L06P Software

repo_url: https://github.com/l06p/supervision_modules_documentation
repo_name: l06p/supervision_modules_documentation

theme: 
  features:
    - navigation.footer
    - navigation.tracking
    - content.code.copy
  name: material
  palette:
    - scheme: slate
      primary: custom
      accent: custom

nav:
  - Accueil: index.md
  - Composition: composition.md
  - Licensing: licensing.md
  - Mise en service: mise_en_service.md
  - Usage des scripts SNMPv2c : usage_snmpv2c.md
  - Usage des scripts SNMPv3 : usage_snmpv3.md
  - "Scripts M2MSoft/generic" : scripts_m2msoft_generic.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format